# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'gamerkit' do
  pod 'LNERadialMenu', '~> 1.0'
  pod 'BNHtmlPdfKit', '~> 0.4'
end

target 'gamerkitTests' do

end

